// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96VznuM87chmknpdWZW1Iif6WnBe_R9o',
    appId: '1:117178325821:web:c23f93af0f1c982522c354',
    messagingSenderId: '117178325821',
    projectId: 'instagram-clone-828f7',
    authDomain: 'instagram-clone-828f7.firebaseapp.com',
    storageBucket: 'instagram-clone-828f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRuXwaEURa09FLXT36tOkvDFVLUlkm-AY',
    appId: '1:117178325821:android:a96ec811ce2cf8fa22c354',
    messagingSenderId: '117178325821',
    projectId: 'instagram-clone-828f7',
    storageBucket: 'instagram-clone-828f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYOZ5aCtmXyKhMkibVDJX5zYwgEQmrtzE',
    appId: '1:117178325821:ios:f2ca516e0d066bde22c354',
    messagingSenderId: '117178325821',
    projectId: 'instagram-clone-828f7',
    storageBucket: 'instagram-clone-828f7.appspot.com',
    iosClientId: '117178325821-anqe1paqkfkqbjg7jb6lgh9n2357ms0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYOZ5aCtmXyKhMkibVDJX5zYwgEQmrtzE',
    appId: '1:117178325821:ios:f2ca516e0d066bde22c354',
    messagingSenderId: '117178325821',
    projectId: 'instagram-clone-828f7',
    storageBucket: 'instagram-clone-828f7.appspot.com',
    iosClientId: '117178325821-anqe1paqkfkqbjg7jb6lgh9n2357ms0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
